import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { trpc } from "../utils/trpc";

import "../styles/globals.css";
import Head from "next/head";
import { MantineProvider } from '@mantine/core';
import { HeaderMegaMenu } from "../components/Header/Header";

const MyApp: AppType<{ session: Session | null }> = ({
    Component,
    pageProps: { session, ...pageProps },
}) => {
    return (
        <>
            <Head>
                <title>Page title</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
            </Head>

            <MantineProvider
                withGlobalStyles
                withNormalizeCSS
                theme={{
                    colorScheme: 'light',
                }}
            >
                <SessionProvider session={session}>
                    <main className="min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                        <HeaderMegaMenu />
                        <Component {...pageProps} />
                    </main>

                </SessionProvider>
            </MantineProvider>
        </>

    );
};

export default trpc.withTRPC(MyApp);
